namespace CollectionApp.Models;

public class Genres{
   public static List<string> AnimeGenres = new List<string>{
      "None",
      "Kodomo",
      "Shonen",
      "Shojo",
      "Seinen",
      "Josei",
      "Harem",
      "Rev Harem",
      "Hentai",
      "Romance",
      "Horror",
      "Comedy",
      "Fanatsy",
      "Ecchi",
      "Mecha",
      "Loli",
      "Shota",
      "Isekai",
      "Yaoi",
      "Yuri",
      "Drama",
      "Supernatural",
      "Thriller",
      "Slice of Life",
      "Adventure",
      "Battle",
      "Magic",
   };

   public static List<string> VideoGameGenres = new List<string>{
      "None",
      "Platform",
      "Shooter",
      "Beat em Up",
      "Fighting",
      "RPG",
      "JRPG",
      "Sim",
      "Strategy",
      "Sports",
      "MMO",
      "Dating Sim",
      "Gatcha",
      "Idle",
      "Racing",
      "Tower Defense",
      "First-Person",
      "Thrid Person",
      "Real Time",
      "Rougelike",
      "Action",
      "Stealth",
      "Survival",
      "Rhythm",
      "Battle Royal",
   };
}